### PR TITLE
Added h[1-6] classes as in Bootstrap 4.

### PR DESCRIPTION
**Pull request by mperrando**
See https://getbootstrap.com/docs/4.1/content/typography/#headings.

### CODE REVIEW

**Comment by stuyam** [comment]
@mperrando should these be added like that or should they be added on the already there h1-h6? For example:
```css
h1, .h1 {
  font-size: 2.25 * $font-size-base;
  line-height: 1.1 * 2.25 * $font-size-base;
}
```
Including the initial formatting? https://github.com/stuyam/bootstrap-email/blob/master/core/sass/_typography.scss#L1

Or should it be left the way you have it and just be a way of scaling font size?

**Comment by mperrando** [comment]
Maybe the best is to follow bootsrap behaviour as best as we can, thus using the strategy you suggest.

If you also agree I can patch this PR accordingly.

By the way, I see that line height should be 1.2 (relative to the font height), is there a reason for it being 1.1?

**Comment by stuyam** [comment]
Bootstrap must have updated their line height since I built this. While you are at it you could probably simplify that code into a loop if possible with a hash like { h1: 2.25 } and loop though to build those. Might be cleaner.

**Comment by mperrando** [comment]
I agree. Anyway, Bootstrap itself keeps those declarations [isolated](https://github.com/twbs/bootstrap/blob/9faf8e85451ebc5981e85bd22d305f5275a4fd24/scss/_type.scss#L7), so maybe  should we do the same for sake of clarity?

I see Bootstrap uses `line-height: $headings-line-height;` (that is 1.2) in the block common to all headings, instead here the height is calculated inside each heading definition. Is this due to the fact that in that way it does not work? Otherwise it would be better to keep that declaration in the common block, wouldn't it?

And what about defining $headings-line-height in variables and using that variable here?

**Comment by stuyam** [comment]
Yes it is an email thing, line heights in email need to be in pixels so that's why it is that way. 😢

**Comment by mperrando** [comment]
I figured that out...

So, we keep the explicit multiplications.

What about defining the variable? that should work and let the user choose a different line height if desired.

**Comment by stuyam** [comment]
Yeah that sounds great

**Comment by mperrando** [comment]
@stuyam I've implemented through a loop as you said.

I also introduced a couple of utility functions that allows the user to extract `font-size` and `line-height` for every heading. I don't know if their place is in the variables file or in th etypography file. Your idea?

All this because I needed to make some text to appear as an heading but without the bottom margin, that I cannot get rid of in any way...

Incidentally, the `m*-*` classes have been lost? they still appear in the documentation, but I cannot find them in the code. Maybe should I open a new ticket about this?

**Comment by stuyam** [comment]
I can see your confusion. If you scroll down to the margin section you can see how they work: https://bootstrapemail.com/docs/spacing

They are only vertical margin and they are basically just helpers around the spacer util classes that make vertical spacing between elements. The margin classes are removed during the compilation process and they are replaced with spacers above and below. Limitations of email and consistent margin.

I see how that is tricky though because in this case we are adding bottom margin on the headers. In some instances like headers margin in consistent, but not always. You should be able to do style="margin-bottom: 0" or something of that nature? I get how that is confusing and complicated, need to brainstorm making that better. I think that might be why I didn't create the .h1-.h6 classes because different elements behave differently in different email clients so margin and such change...

need to think on all of this

**Comment by mperrando** [comment]
Anyway, the new h's classes pose no threat: they correspond to the official ones of Bootstrap 4, and are at all identical to the h's tags.

If you like the implementation, there should be no problem in merging this.

Another thing is to try to force the margins without using spacers. This is the reason why maybe it is better to treat this other issue in a separate place.

**Comment by stuyam** [comment]
Well the h's classes might not work on everything because h's are the few things that consistently work with top and bottom margin so if you apply an h class to a different element it might not consistently work is all. I'm now remembering because it used to be build in but because of that complexity I took it out.

I'm ok with putting it in it's just not perfect. Definitely open an issue with the margin spacing stuff Im happy to work through that, it can be pretty tricky but I am open to ideas.

**Comment by stuyam** [comment]
I am going to merge this, I also am removing all default margins from the few elements that have it such as headers and alerts because it can always be additive with the margin spacers but harder to remove. Coming in the next release.

**Comment by stuyam** [comment]
Great work on that pull request, thank you!

**Comment by mperrando** [comment]
You're very welcome.

**Pull request merged**
